const SKIP_SELECTOR = [
    '.player-controls',
    '.now-playing-bar .track-info',
    '.track-list',
    '.track-item',
    '.queue-track-item',
    '.card-title',
    '.card-subtitle',
    '.card-artist',
    '.card-info',
    '.sidebar-library-list',
    '.sidebar-library-item',
    '.search-results-dropdown',
    '.lyrics-page-content',
    '.fullscreen-lyrics-content',
    '.fullscreen-lyrics-pane',
    'am-lyrics',
    '[data-user-content]',
    '[data-no-translate]',
    'script',
    'style',
    'code',
    'pre',
    'textarea',
].join(', ');

const exactTranslations = new Map(
    Object.entries({
        'Waves': 'Waves Music',
        'Play': 'נגן',
        'Pause': 'השהה',
        'Shuffle play': 'ניגון אקראי',
        'Start radio': 'התחל רדיו',
        'Mix track': 'מיקס לשיר',
        'Start mix': 'התחל מיקס',
        'Play next': 'נגן הבא',
        'Add to queue': 'הוסף לתור',
        'Like': 'אהבתי',
        'Pin': 'נעץ',
        'Mark as favorite': 'סמן כמועדף',
        'Add to playlist': 'הוסף לפלייליסט',
        'Request song': 'בקש שיר',
        'Go to artist': 'עבור לאמן',
        'Go to album': 'עבור לאלבום',
        'Copy link': 'העתק קישור',
        'Open original URL': 'פתח קישור מקורי',
        'Playlist Order': 'סדר הפלייליסט',
        'Date Added (Newest)': 'תאריך הוספה (החדש ביותר)',
        'Date Added (Oldest)': 'תאריך הוספה (הישן ביותר)',
        'Title (A-Z)': 'שם (א-ת)',
        'Artist (A-Z)': 'אמן (א-ת)',
        'Album (A-Z)': 'אלבום (א-ת)',
        'Stereo': 'סטריאו',
        'Mid': 'מרכז',
        'Side': 'צד',
        'Low Shelf': 'מדף נמוך',
        'Peaking': 'שיא',
        'High Shelf': 'מדף גבוה',
        'Add Node': 'הוסף נקודה',
        'Panel': 'פאנל',
        'Up Next': 'הבא בתור',
        'Auto': 'אוטומטי',
        'Lyrics appear here.': 'המילים יופיעו כאן.',
        'Create Playlist': 'צור פלייליסט',
        'Playlist name': 'שם הפלייליסט',
        'Cover image URL': 'קישור לתמונת עטיפה',
        'תיאור (לא חובה)': 'תיאור (אופציונלי)',
        'Upload': 'העלה',
        'or URL': 'או קישור',
        'Import from CSV': 'ייבוא מ-CSV',
        'Import from JSPF': 'ייבוא מ-JSPF',
        'Import from XSPF': 'ייבוא מ-XSPF',
        'Import from XML': 'ייבוא מ-XML',
        'Import from M3U/M3U8': 'ייבוא מ-M3U/M3U8',
        'Please use': 'נא להשתמש ב-',
        'to export your Spotify playlist into a .csv.': 'כדי לייצא פלייליסט של Spotify לקובץ .csv.',
        'to export your Apple Music playlist into a .csv.': 'כדי לייצא פלייליסט של Apple Music לקובץ .csv.',
        '(Apple Music imports are prone to errors)': '(ייבוא מ-Apple Music עלול לכלול שגיאות)',
        'Paste a YouTube Music Playlist URL.': 'הדבק קישור לפלייליסט של YouTube Music.',
        'Make sure its headers are in English.': 'ודא שכותרות הקובץ באנגלית.',
        'Strict Album Matching': 'התאמת אלבום מדויקת',
        'Album name should strictly match CSV metadata. Disable for better discovery.':
            'שם האלבום חייב להתאים בדיוק למטא-דאטה ב-CSV. כבה זאת כדי לשפר איתור.',
        'Warning:': 'אזהרה:',
        "This feature isn't perfect and is prone to errors! Please check your playlist after to remove any unwanted songs that were added by the system.":
            'האפשרות הזו אינה מושלמת ועלולות להיות שגיאות. בדקו את הפלייליסט לאחר הייבוא והסירו שירים לא רצויים.',
        'Share': 'שתף',
        'Cancel': 'ביטול',
        'Save': 'שמור',
        'Edit Profile': 'עריכת פרופיל',
        'Username': 'שם משתמש',
        'Display Name': 'שם תצוגה',
        'Avatar URL': 'קישור לתמונת פרופיל',
        'Banner URL': 'קישור לבאנר',
        'Status (Listening to...)': 'סטטוס (מאזין/ה ל...)',
        'Favorite Albums (Max 5)': 'אלבומים אהובים (עד 5)',
        'About Me': 'עליי',
        'Website': 'אתר',
        'Last.fm Username': 'שם משתמש ב-Last.fm',
        'Privacy': 'פרטיות',
        'Public Playlists': 'פלייליסטים ציבוריים',
        'Save Profile': 'שמור פרופיל',
        'Create Folder': 'צור תיקייה',
        'Email Authentication': 'אימות באימייל',
        'Forgot password?': 'שכחת סיסמה?',
        'Sign In': 'התחברות',
        'Sign Up': 'הרשמה',
        'Sign In / Sign Up': 'התחברות / הרשמה',
        'Add to Playlist': 'הוסף לפלייליסט',
        'Go to Playlist': 'עבור לפלייליסט',
        'Keyboard Shortcuts': 'קיצורי מקשים',
        'Play / Pause': 'נגן / השהה',
        'Seek forward 10s': 'דלג 10 שניות קדימה',
        'Seek backward 10s': 'דלג 10 שניות אחורה',
        'Next track': 'השיר הבא',
        'Previous track': 'השיר הקודם',
        'Volume up': 'הגבר עוצמה',
        'Volume down': 'הנמך עוצמה',
        'Mute / Unmute': 'השתק / בטל השתקה',
        'Toggle shuffle': 'הפעל/כבה ערבוב',
        'Toggle repeat': 'הפעל/כבה חזרה',
        'Open queue': 'פתח תור',
        'Toggle lyrics': 'הצג/הסתר מילים',
        'Focus search': 'התמקד בחיפוש',
        'Close modals': 'סגור חלונות',
        'Customize Shortcuts': 'התאמת קיצורים',
        'Reset to Defaults': 'איפוס לברירת מחדל',
        'Done': 'סיום',
        'Note': 'הערה',
        'Missing Tracks:': 'שירים חסרים:',
        'Copy to Clipboard': 'העתק ללוח',
        'Export as CSV': 'ייצא כ-CSV',
        'OK': 'אישור',
        'Download Discography': 'הורד דיסקוגרפיה',
        'Custom Database/Auth': 'מסד נתונים/אימות מותאם',
        'Save & Reload': 'שמור וטען מחדש',
        'Theme Store': 'חנות ערכות נושא',
        'Browse': 'עיון',
        'Back': 'חזרה',
        'Apply Theme': 'החל ערכת נושא',
        'Description': 'תיאור',
        'Go to Login': 'עבור להתחברות',
        'Theme Name': 'שם ערכת נושא',
        'Author Website (Optional)': 'אתר היוצר (אופציונלי)',
        'CSS': 'CSS',
        'Font...': 'גופן...',
        'System': 'מערכת',
        'Mono': 'מונו',
        'Serif': 'סריף',
        'Radius...': 'רדיוס...',
        'Square': 'מרובע',
        'Small': 'קטן',
        'Medium': 'בינוני',
        'Large': 'גדול',
        'Template': 'תבנית',
        'Preview': 'תצוגה מקדימה',
        'Cancel Edit': 'בטל עריכה',
        'Upload Theme': 'העלה ערכת נושא',
        'Unreleased Project': 'פרויקט שלא שוחרר',
        'Close': 'סגור',
        'Title': 'שם',
        'Duration': 'משך',
        'Menu': 'תפריט',
        'Update Available': 'יש עדכון זמין',
        'A new version of Waves is available.': 'גרסה חדשה של Waves Music זמינה.',
        'Later': 'מאוחר יותר',
        'Update Now': 'עדכן עכשיו',
        'Importing Tracks from CSV': 'מייבא שירים מ-CSV',
        'Preparing import...': 'מכין ייבוא...',
        'tracks processed': 'שירים עובדו',
        'Your Library': 'הספרייה שלך',
        'Your Library is empty': 'הספרייה שלך ריקה',
        'Create': 'צור',
        'Playlists': 'פלייליסטים',
        'Artists': 'אמנים',
        'Albums': 'אלבומים',
        'Home': 'בית',
        'Hot & New': 'חם וחדש',
        'Welcome to Waves': 'ברוכים הבאים ל-Waves Music',
        "You haven't listened to anything yet. Search for your favorite songs to get started!":
            'עדיין לא האזנת לשום דבר. חפשו את השירים האהובים עליכם כדי להתחיל.',
        'Recommended Songs': 'שירים מומלצים',
        'No song recommendations found.': 'לא נמצאו המלצות לשירים.',
        'Start Infinite Radio': 'התחל רדיו אינסופי',
        'Recommended Albums': 'אלבומים מומלצים',
        'Recommended Artists': 'אמנים מומלצים',
        'Listen to more music to get artist recommendations.': 'האזינו לעוד מוזיקה כדי לקבל המלצות לאמנים.',
        'Jump Back In': 'חזור להאזנה',
        'Name': 'שם',
        'Recently Added': 'נוספו לאחרונה',
        'Popular Playlists': 'פלייליסטים פופולריים',
        'Popularity': 'פופולריות',
        'Most Played': 'הכי מושמעים',
        'Listening Parties': 'מסיבות האזנה',
        'Listening Party': 'מסיבת האזנה',
        'Create Listening Party': 'צור מסיבת האזנה',
        'Party Name': 'שם המסיבה',
        'Leave Party': 'עזוב מסיבה',
        'Copy Invite Link': 'העתק קישור הזמנה',
        'Currently Playing': 'מתנגן עכשיו',
        'Participants (': 'משתתפים (',
        'Song Requests': 'בקשות שירים',
        'Chat': 'צ׳אט',
        'Send': 'שלח',
        'Search Results': 'תוצאות חיפוש',
        'All': 'הכל',
        'Tracks': 'שירים',
        'My Playlists': 'הפלייליסטים שלי',
        'Create playlist': 'צור פלייליסט',
        'Favorites': 'מועדפים',
        'Liked Tracks': 'שירים שאהבתי',
        'Playlists and Mixes': 'פלייליסטים ומיקסים',
        'Local Files': 'קבצים מקומיים',
        'Select Music Folder': 'בחר תיקיית מוזיקה',
        'Change Folder': 'החלף תיקייה',
        'Recently played': 'הושמעו לאחרונה',
        'Clear': 'נקה',
        'Unreleased Artist': 'אמן עם חומרים שלא שוחררו',
        'Shuffle Play': 'ניגון אקראי',
        'Play Album': 'נגן אלבום',
        'Shuffle': 'ערבוב',
        'Radio': 'רדיו',
        'Mix': 'מיקס',
        'from Artist': 'מהאמן',
        'EPs and Singles': 'EP וסינגלים',
        'Similar Artists': 'אמנים דומים',
        'Similar Albums': 'אלבומים דומים',
        'Suggested Songs From Your Playlist': 'שירים מוצעים מהפלייליסט שלך',
        'Delete Folder': 'מחק תיקייה',
        'In Your Library': 'בספרייה שלך',
        'Popular Tracks': 'שירים פופולריים',
        'Load Unreleased Projects': 'טען פרויקטים שלא שוחררו',
        'Unreleased Music': 'מוזיקה שלא שוחררה',
        'Song': 'שיר',
        'Lyrics': 'מילים',
        'More from Album': 'עוד מהאלבום',
        'Similar Tracks': 'שירים דומים',
        'Play a song to see lyrics.': 'נגנו שיר כדי לראות מילים.',
        'User': 'משתמש',
        'Favorite Albums of All Time': 'אלבומים אהובים מכל הזמנים',
        'Recent Scrobbling': 'השמעות אחרונות',
        'Powered by Last.fm': 'מופעל על ידי Last.fm',
        'Top Artists': 'אמנים מובילים',
        'Top Albums': 'אלבומים מובילים',
        'Top Tracks': 'שירים מובילים',
        'Settings': 'הגדרות',
        'Appearance': 'מראה',
        'Interface': 'ממשק',
        'Scrobbling': 'סקראבלינג',
        'Audio': 'שמע',
        'Admin': 'ניהול',
        'Theme': 'ערכת נושא',
        'Choose your preferred color scheme': 'בחר ערכת צבעים מועדפת',
        'Black': 'שחור',
        'White': 'לבן',
        'Dark': 'כהה',
        'Ocean': 'אוקיינוס',
        'Purple': 'סגול',
        'Forest': 'יער',
        'Custom': 'מותאם',
        'Applied Community Theme': 'ערכת קהילה פעילה',
        'Unapply Theme': 'בטל ערכת נושא',
        'Custom Theme': 'ערכת נושא מותאמת',
        'Reset': 'איפוס',
        'Community Themes': 'ערכות נושא מהקהילה',
        'Open Theme Store': 'פתח חנות ערכות נושא',
        'Font': 'גופן',
        'Preset': 'קבוע מראש',
        'Google Fonts': 'Google Fonts',
        'URL': 'קישור',
        'Apply': 'החל',
        'Font Size': 'גודל גופן',
        'Waveform Seekbar': 'סרגל התקדמות גלי',
        'Album Cover Background': 'רקע עטיפת אלבום',
        'Dynamic Colors': 'צבעים דינמיים',
        'No Round Album Cover': 'עטיפה ללא עיגול פינות',
        'Vanilla Tilt Album Cover': 'הטיית עטיפה תלת-ממדית',
        'Tilt Distance': 'מרחק הטיה',
        'Tilt Speed': 'מהירות הטיה',
        'Full-screen Visualizer': 'ויזואלייזר במסך מלא',
        'Visualizer Style': 'סגנון ויזואלייזר',
        'Visualizer Mode': 'מצב ויזואלייזר',
        'Solid Background': 'רקע אחיד',
        'Blended on Cover Art': 'משולב על עטיפת האלבום',
        'Smart Intensity Switching': 'החלפת עוצמה חכמה',
        'Visualizer Sensitivity': 'רגישות ויזואלייזר',
        'Visualizer Brightness': 'בהירות ויזואלייזר',
        'Cycle Presets': 'החלף תבניות אוטומטית',
        'Current Preset': 'תבנית נוכחית',
        'Loading...': 'טוען...',
        'Cycle Duration': 'משך החלפה',
        'Randomize Presets': 'בחר תבניות באקראי',
        'Show Recommended Songs': 'הצג שירים מומלצים',
        'Show Recommended Albums': 'הצג אלבומים מומלצים',
        'Show Recommended Artists': 'הצג אמנים מומלצים',
        'Show Jump Back In': 'הצג חזרה להאזנה',
        "Show Editor's Picks": 'הצג בחירות עורכים',
        'Compact Artists': 'כרטיסי אמנים קומפקטיים',
        'Artist Banners': 'באנרים של אמנים',
        'Compact Albums': 'כרטיסי אלבומים קומפקטיים',
        'TOP SECTION': 'אזור עליון',
        'BOTTOM SECTION': 'אזור תחתון',
        'Now Playing View Mode': 'מצב תצוגת מתנגן עכשיו',
        'Fullscreen Mode': 'מצב מסך מלא',
        'Lyrics Panel': 'פאנל מילים',
        'Exit fullscreen mode': 'צא ממסך מלא',
        'Hide UI': 'הסתר ממשק',
        'Pause/resume track': 'השהה/המשך שיר',
        'Skip song': 'דלג שיר',
        'Previous song': 'שיר קודם',
        'Do nothing': 'אל תעשה כלום',
        'Scrobble Threshold': 'סף סקראבלינג',
        'Last.fm Scrobbling': 'סקראבלינג ל-Last.fm',
        'Connect Last.fm': 'חבר Last.fm',
        'Enable Scrobbling': 'הפעל סקראבלינג',
        'Custom API Credentials': 'פרטי API מותאמים',
        'API Key': 'מפתח API',
        'API Secret': 'סוד API',
        'Save Credentials': 'שמור פרטי גישה',
        'Login with Credentials': 'התחבר עם פרטי גישה',
        'Login': 'התחבר',
        'Use Standard': 'השתמש ברגיל',
        'Streaming Quality': 'איכות הזרמה',
        'Download Quality': 'איכות הורדה',
        'Show Quality Badges': 'הצג תגי איכות',
        'Gapless Playback': 'ניגון רציף',
        'Off': 'כבוי',
        'Track': 'שיר',
        'Album': 'אלבום',
        'Low': 'נמוך',
        'High': 'גבוה',
        'EQ Studio': 'סטודיו EQ',
        'Legacy EQ': 'EQ ישן',
        'Parametric EQ': 'EQ פרמטרי',
        'AutoEQ': 'AutoEQ',
        'Speaker EQ': 'EQ לרמקולים',
        'Bands': 'תחומים',
        'Flat': 'שטוח',
        'Bass Boost': 'הגברת בס',
        'Bass Reducer': 'הפחתת בס',
        'Treble Boost': 'הגברת טרבל',
        'Treble Reducer': 'הפחתת טרבל',
        'Vocal Boost': 'הגברת קול',
        'Loudness': 'עוצמה',
        'Rock': 'רוק',
        'Pop': 'פופ',
        'Classical': 'קלאסי',
        'Jazz': 'ג׳אז',
        'Electronic': 'אלקטרוני',
        'Hip-Hop': 'היפ-הופ',
        'Acoustic': 'אקוסטי',
        'Speech': 'דיבור',
        'Delete': 'מחק',
        'Preamp': 'קדם מגבר',
        'Frequency Response': 'תגובת תדר',
        'Original': 'מקורי',
        'Corrected': 'מתוקן',
        'Database': 'מסד נתונים',
        'Select a headphone...': 'בחר אוזניות...',
        'SAVED PROFILES': 'פרופילים שמורים',
        'Download Lyrics': 'הורד מילים',
        'Romaji Lyrics': 'מילים ברומאג׳י',
        'Cover Art Size': 'גודל עטיפה',
        'Filename Template': 'תבנית שם קובץ',
        'Folder Template': 'תבנית תיקייה',
        'Generate M3U': 'צור M3U',
        'Generate M3U8': 'צור M3U8',
        'Generate CUE': 'צור CUE',
        'Generate NFO': 'צור NFO',
        'Generate JSON': 'צור JSON',
        'Relative Paths': 'נתיבים יחסיים',
        'Separate Discs': 'הפרד דיסקים',
        'Include Cover File': 'כלול קובץ עטיפה',
        'Customize': 'התאמה אישית',
        'Cache': 'מטמון',
        'Clear Cache': 'נקה מטמון',
        'Auto-Update App': 'עדכון אוטומטי',
        'Analytics': 'אנליטיקה',
        'Reset Local Data': 'אפס נתונים מקומיים',
        'Clear Cloud Data': 'מחק נתוני ענן',
        'Backup & Restore': 'גיבוי ושחזור',
        'Export All Settings': 'ייצא את כל ההגדרות',
        'Blocked Content': 'תוכן חסום',
        'Manage': 'ניהול',
        'Clear All': 'נקה הכל',
        'Nothing blocked yet.': 'עדיין אין חסימות.',
        'DEV MODE': 'מצב פיתוח',
        'Dev Mode': 'מצב פיתוח',
        'CUSTOM DATABASE & AUTH': 'מסד נתונים ואימות מותאמים',
        'ADVANCED: Custom Database/Auth': 'מתקדם: מסד נתונים/אימות מותאם',
        'Configure': 'הגדר',
        'API INSTANCES': 'מופעי API',
        'API Instances': 'מופעי API',
        'Refresh Instance List': 'רענן רשימת מופעים',
        'LIBRARY SCANNING': 'סריקת ספרייה',
        'Library Scanning': 'סריקת ספרייה',
        'Rescan Library': 'סרוק ספרייה מחדש',
        'RECOMMENDATIONS SERVER': 'שרת המלצות',
        'Server Status': 'סטטוס שרת',
        'Checking recommendation server...': 'בודק שרת המלצות...',
        'Refresh Status': 'רענן סטטוס',
        'Catalog Mirror': 'מראת קטלוג',
        'Unknown': 'לא ידוע',
        'Audio Scan': 'סריקת שמע',
        'Signals': 'אותות',
        'Precomputed Neighbors': 'שכנים מחושבים מראש',
        'Music Recommendations': 'המלצות מוזיקה',
        'Retrigger Recommendations': 'הרץ המלצות מחדש',
        'Active Model': 'מודל פעיל',
        'Status': 'סטטוס',
        'Sign Up / Sign In': 'הרשמה / התחברות',
        'View My Profile': 'הצג את הפרופיל שלי',
        'Support Waves': 'תמכו ב-Waves Music',
        'Donate on Ko-fi': 'תרומה ב-Ko-fi',
        'Star on GitHub': 'כוכב ב-GitHub',
        'Reset your Password': 'איפוס סיסמה',
        'Reset Password': 'אפס סיסמה',
        'Select a song': 'בחר שיר',
        'Please sign in to your ecosystem': 'התחברו לספריית המוזיקה שלכם',
        'Password': 'סיסמה',
        ['Powered by ' + 'Spoti' + 'man Music Ecosystem']: 'מופעל על ידי Waves Music',
        'Save album to library': 'שמור אלבום בספרייה',
        'Remove album from library': 'הסר אלבום מהספרייה',
        'Save playlist to library': 'שמור פלייליסט בספרייה',
        'Remove playlist from library': 'הסר פלייליסט מהספרייה',
        'Remove from favorites': 'הסר מהמועדפים',
        'Dismiss fullscreen': 'סגור מסך מלא',
        'Hide Lyrics': 'הסתר מילים',
        'Toggle UI': 'הצג/הסתר ממשק',
        'Disable Visualizer': 'כבה ויזואלייזר',
        'Album Cover': 'עטיפת אלבום',
        'Queue': 'תור',
        'Add to favorites': 'הוסף למועדפים',
        'Previous': 'הקודם',
        'Next': 'הבא',
        'Repeat': 'חזרה',
        'Quality': 'איכות',
        'Mute': 'השתק',
        'Switch to URL input': 'עבור להזנת קישור',
        'Search for a song or album...': 'חפש שיר או אלבום...',
        'Search for an album...': 'חפש אלבום...',
        'Tell us about yourself': 'ספרו על עצמכם',
        'Folder name': 'שם תיקייה',
        'Icon URL (optional)': 'קישור לאייקון (אופציונלי)',
        'Email Address': 'כתובת אימייל',
        'Search themes...': 'חפש ערכות נושא...',
        'My Awesome Theme': 'ערכת הנושא שלי',
        'Describe your theme...': 'תארו את ערכת הנושא...',
        'Background': 'רקע',
        'Foreground': 'חזית',
        'Primary': 'ראשי',
        'Secondary': 'משני',
        'Accent/Highlight': 'הדגשה',
        'Card Background': 'רקע כרטיס',
        'Border Color': 'צבע גבול',
        'Muted Text': 'טקסט משני',
        'Font Family': 'משפחת גופנים',
        'Custom Font...': 'גופן מותאם...',
        'Border Radius': 'רדיוס גבול',
        'Search commands, music, settings...': 'חפש פקודות, מוזיקה והגדרות...',
        'Command palette search': 'חיפוש בלוח הפקודות',
        'Waves Logo': 'לוגו Waves Music',
        'Open navigation': 'פתח ניווט',
        'Search for tracks, artists, albums...': 'חפש שירים, אמנים ואלבומים...',
        'Clear search': 'נקה חיפוש',
        'Go Back': 'חזור',
        'Go Forward': 'קדימה',
        'Account': 'חשבון',
        'Collapse sidebar': 'כווץ סרגל צד',
        'Search in Your Library': 'חיפוש בספרייה שלך',
        'Refresh': 'רענן',
        'Clear History': 'נקה היסטוריה',
        'Say something...': 'כתוב משהו...',
        'Search liked tracks...': 'חפש בשירים שאהבתי...',
        'List view': 'תצוגת רשימה',
        'Card view': 'תצוגת כרטיסים',
        'Shuffle Liked Tracks': 'ערבב שירים שאהבתי',
        'Album Radio': 'רדיו אלבום',
        'Save to Favorites': 'שמור במועדפים',
        'More options': 'אפשרויות נוספות',
        'Playlist Cover': 'עטיפת פלייליסט',
        'Search tracks...': 'חפש שירים...',
        'Refresh Recommendations': 'רענן המלצות',
        'Folder Cover': 'עטיפת תיקייה',
        'Mix Cover': 'עטיפת מיקס',
        'Artist': 'אמן',
        'Artist Radio': 'רדיו אמן',
        'Track Cover': 'עטיפת שיר',
        'Song Radio': 'רדיו שיר',
        'Avatar': 'תמונת פרופיל',
        'Search settings...': 'חפש בהגדרות...',
        'Enter username': 'הזן שם משתמש',
        'Enter password': 'הזן סיסמה',
        'Open lyrics page': 'פתח עמוד מילים',
        'Track Mix': 'מיקס שיר',
        'Open fullscreen': 'פתח מסך מלא',
    })
);

const translatableAttributes = [
    'title',
    'aria-label',
    'alt',
    'placeholder',
    'data-label-album',
    'data-label-unlike-album',
    'data-label-playlist',
    'data-label-unlike-playlist',
    'data-label-track',
    'data-label-unlike-track',
    'data-label-video',
    'data-label-unlike-video',
];

function shouldSkip(node) {
    const element = node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement;
    return !element || Boolean(element.closest(SKIP_SELECTOR));
}

function translateText(value) {
    if (!value || !/[A-Za-z]/.test(value)) return value;
    const trimmed = value.trim();
    const exact = exactTranslations.get(trimmed);
    if (exact) return value.replace(trimmed, exact);

    const translated = value.replace(new RegExp('spoti' + 'man', 'gi'), 'Waves Music');
    return translated;
}

function translateTextNode(node) {
    if (shouldSkip(node)) return;
    const translated = translateText(node.nodeValue);
    if (translated !== node.nodeValue) node.nodeValue = translated;
}

function translateElement(element) {
    if (shouldSkip(element)) return;
    for (const attr of translatableAttributes) {
        if (!element.hasAttribute(attr)) continue;
        const current = element.getAttribute(attr);
        const translated = translateText(current);
        if (translated !== current) element.setAttribute(attr, translated);
    }
}

function walk(root = document.body) {
    if (!root) return;
    if (root.nodeType === Node.TEXT_NODE) {
        translateTextNode(root);
        return;
    }
    if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_FRAGMENT_NODE) return;
    if (root.nodeType === Node.ELEMENT_NODE) translateElement(root);

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT, {
        acceptNode(node) {
            return shouldSkip(node) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT;
        },
    });

    let node = walker.nextNode();
    while (node) {
        if (node.nodeType === Node.TEXT_NODE) translateTextNode(node);
        else translateElement(node);
        node = walker.nextNode();
    }
}

function applyHebrewUI() {
    document.documentElement.lang = 'he';
    document.documentElement.dir = 'rtl';
    document.title = 'Waves Music';
    walk();
}

const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
        if (mutation.type === 'characterData') {
            translateTextNode(mutation.target);
            continue;
        }
        if (mutation.type === 'attributes') {
            translateElement(mutation.target);
            continue;
        }
        for (const node of mutation.addedNodes) {
            walk(node);
        }
    }
});

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', applyHebrewUI, { once: true });
} else {
    applyHebrewUI();
}

observer.observe(document.documentElement, {
    childList: true,
    subtree: true,
    characterData: true,
    attributes: true,
    attributeFilter: translatableAttributes,
});
