server {
    listen 4173;
    listen [::]:4173;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(?:css|js|mjs|map|json|wasm|mp3|flac|wav|ogg|png|jpg|jpeg|svg|webp|ico|gz|br|utf|ttf|woff2?)$ {
        try_files $uri =404;
    }

    location /api/v1/recommend/ {
        proxy_pass ${NAVIDROME_URL};
    }

    location /rest/ {
        proxy_pass ${NAVIDROME_URL};
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
