name: Update Lock File

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-lock:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Configure Git
              uses: DanTheMan827/config-git-user-action@v1

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'yarn'

            - name: Install dependencies
              run: |
                  corepack enable
                  yarn install

            - name: Commit changes
              run: |
                  git add -A . || true
                  git commit "update lockfile" || true
                  git push || true
